general:
  printStackTraces: true
  showQueries: true
  debugMessages: true
database:
  username: minecraft
  password: minecraft
  host: localhost
  port: 3306
  database: creative
  prefix: CoEBlockRegen_
blocks:
    COAL_ORE:
        replace: BEDROCK
        regenerate-time: 86400
        replace-time: 2
        money: 0
        min: 1
        max: 1
        track-players: true
        tools-required:
            - WOOD_PICKAXE
            - STONE_PICKAXE
            - IRON_PICKAXE
            - GOLD_PICKAXE
            - DIAMOND_PICKAXE
        but-not-in-worlds: []
    IRON_ORE:
        replace: BEDROCK
        regenerate-time: 86400
        replace-time: 2
        money: 0
        min: 1
        max: 1
        track-players: true
        tools-required:
            - WOOD_PICKAXE
            - STONE_PICKAXE
            - IRON_PICKAXE
            - GOLD_PICKAXE
            - DIAMOND_PICKAXE
        but-not-in-worlds: []
    GOLD_ORE:
        replace: BEDROCK
        regenerate-time: 86400
        replace-time: 2
        money: 1
        min: 1
        max: 1
        track-players: true
        tools-required:
            - IRON_PICKAXE
            - GOLD_PICKAXE
            - DIAMOND_PICKAXE
        but-not-in-worlds: []
    LAPIS_ORE:
        replace: BEDROCK
        regenerate-time: 5
        replace-time: 2
        money: 0
        min: 1
        max: 1
        track-players: true
        tools-required:
            - STONE_PICKAXE
            - IRON_PICKAXE
            - GOLD_PICKAXE
            - DIAMOND_PICKAXE
        but-not-in-worlds: []
    REDSTONE_ORE:
        replace: BEDROCK
        regenerate-time: 86400
        replace-time: 2
        money: 0
        min: 1
        max: 1
        track-players: true
        tools-required:
            - IRON_PICKAXE
            - GOLD_PICKAXE
            - DIAMOND_PICKAXE
        but-not-in-worlds: []
    GLOWING_REDSTONE_ORE:
        replace: BEDROCK
        regenerate-time: 86400
        replace-time: 2
        money: 0
        min: 1
        max: 1
        track-players: true
        tools-required:
            - IRON_PICKAXE
            - GOLD_PICKAXE
            - DIAMOND_PICKAXE
        but-not-in-worlds: []
    EMERALD_ORE:
        replace: BEDROCK
        regenerate-time: 86400
        replace-time: 2
        money: 0
        min: 1
        max: 1
        track-players: true
        tools-required:
            - IRON_PICKAXE
            - GOLD_PICKAXE
            - DIAMOND_PICKAXE
        but-not-in-worlds: []
    DIAMOND_ORE:
        replace: BEDROCK
        regenerate-time: 86400
        replace-time: 2
        money: 0
        min: 1
        max: 1
        track-players: true
        tools-required:
            - IRON_PICKAXE
            - DIAMOND_PICKAXE
        but-not-in-worlds: []
    GLOWSTONE:
        replace: BEDROCK
        regenerate-time: 86400
        replace-time: 2
        money: 0
        min: 1
        max: 1
        track-players: true
        tools-required:
            - WOOD_PICKAXE
            - STONE_PICKAXE
            - IRON_PICKAXE
            - GOLD_PICKAXE
            - DIAMOND_PICKAXE
        but-not-in-worlds: []
    SOUL_SAND:
        replace: BEDROCK
        regenerate-time: 86400
        replace-time: 2
        money: 0
        min: 1
        max: 4
        track-players: true
        tools-required:
            - WOOD_SHOVEL
            - STONE_SHOVEL
            - IRON_SHOVEL
            - GOLD_SHOVEL
            - DIAMOND_SHOVEL
        but-not-in-worlds: []
    QUARTZ_ORE:
        replace: BEDROCK
        regenerate-time: 86400
        replace-time: 2
        money: 0
        min: 1
        max: 1
        track-players: true
        tools-required:
            - WOOD_PICKAXE
            - STONE_PICKAXE
            - IRON_PICKAXE
            - GOLD_PICKAXE
            - DIAMOND_PICKAXE
        but-not-in-worlds: []